# Generated by Django 2.2.16 on 2022-03-16 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Заказы'},
        ),
    ]
