# Generated by Django 2.2.16 on 2022-03-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20220316_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_order',
            field=models.CharField(choices=[('processing', 'В обработке'), ('collecting', 'Заказ собран'), ('sent', 'Заказ отправлен')], default='processing', max_length=20),
        ),
    ]
