# Generated by Django 2.2.16 on 2022-02-17 12:25

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_seller'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('seller')), name='dont_buy_yourself'),
        ),
    ]
