# Generated by Django 2.2.16 on 2022-02-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20220217_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
