# Generated by Django 2.2.16 on 2022-02-19 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
