# Generated by Django 3.2.12 on 2022-02-13 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_backend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetaGroup',
        ),
    ]
