# Generated by Django 2.2.16 on 2022-02-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_backend', '0003_auto_20220216_2328'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'product_group'), name='unique_name_product_group'),
        ),
    ]
