# Generated by Django 2.2.16 on 2022-02-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_backend', '0004_auto_20220217_1525'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_name_product_group',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'product_seller', 'product_group'), name='unique_name_product_seller_product_group'),
        ),
    ]
