# Generated by Django 2.2.16 on 2022-02-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_backend', '0005_auto_20220217_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
