# Generated by Django 2.2.16 on 2022-04-04 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_backend', '0007_auto_20220331_1919'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_name_product_seller_product_group',
        ),
    ]
